module.exports={
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    PRODUCT_COLLECTION:'product',
    PRODUCT_CATEGORY:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    COUPON_COLLECTION:'coupon'
}